export const ROUTES = {
  HOME: "/",
  PRICING: "/pricing",
  ABOUT: "/about",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  AGENTS: "/dashboard/agents",
  AGENT_NEW: "/dashboard/agents/new",
  AGENT_DETAIL: (id: string) => `/dashboard/agents/${id}`,
  AGENT_EDIT: (id: string) => `/dashboard/agents/${id}/edit`,
  AGENT_BUILDER: (id: string) => `/dashboard/agents/${id}/builder`,
  AGENT_LOGS: (id: string) => `/dashboard/agents/${id}/logs`,
  AGENT_SETTINGS: (id: string) => `/dashboard/agents/${id}/settings`,
  MARKETPLACE: "/dashboard/marketplace",
  MARKETPLACE_DETAIL: (id: string) => `/dashboard/marketplace/${id}`,
  INTEGRATIONS: "/dashboard/integrations",
  KNOWLEDGE: "/dashboard/knowledge",
  KNOWLEDGE_DETAIL: (id: string) => `/dashboard/knowledge/${id}`,
  WORKFORCE: "/dashboard/workforce",
  WORKFORCE_NEW: "/dashboard/workforce/new",
  WORKFORCE_DETAIL: (id: string) => `/dashboard/workforce/${id}`,
  WORKFLOWS: "/dashboard/workflows",
  WORKFLOW_DETAIL: (id: string) => `/dashboard/workflows/${id}`,
  ANALYTICS: "/dashboard/analytics",
  SETTINGS: "/dashboard/settings",
} as const;
